# Generated by Django 5.2 on 2025-04-13 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecordTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, unique=True)),
                ('config', models.TextField()),
                ('is_manager_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_name', models.CharField(max_length=255)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.entitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digiledger.contactinformation')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.entitytype')),
                ('login_credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digiledger.logincredentials')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255)),
                ('monetary_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('encoded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.users')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.recordtypes')),
                ('generated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.users')),
            ],
        ),
        migrations.CreateModel(
            name='RecordToTransactionRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.financialrecords')),
                ('related_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.financialtransactions')),
            ],
            options={
                'unique_together': {('record', 'related_transaction')},
            },
        ),
        migrations.CreateModel(
            name='StatementToRecordRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_records', to='digiledger.financialrecords')),
                ('statement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_records', to='digiledger.financialrecords')),
            ],
            options={
                'unique_together': {('statement_record', 'related_record')},
            },
        ),
    ]
