# Generated by Django 5.2 on 2025-04-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('monetary_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50)),
                ('date_of_entry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digiledger.digiledgerusers')),
                ('record_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.recordaccount')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.section')),
            ],
        ),
    ]
