# Generated by Django 5.2 on 2025-04-19 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='entry_by',
            new_name='ent_by',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_of_entry',
            new_name='ent_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='monetary_value',
            new_name='mon_val',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='reference_id',
            new_name='ref_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='entry_type',
            new_name='side',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='record_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='digiledger.recordaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_transactions', to='digiledger.recordaccount'),
            preserve_default=False,
        ),
    ]
