# Generated by Django 5.2 on 2025-04-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='DigiledgerUsers',
        ),
    ]
