# Generated by Django 5.2 on 2025-04-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0002_recordaccount_section_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DigiledgerUsers',
            new_name='DigiledgerUser',
        ),
        migrations.RenameModel(
            old_name='LoginCredentials',
            new_name='LoginCredential',
        ),
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
    ]
