# Generated by Django 5.2 on 2025-04-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0004_transaction_dsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
    ]
