# Generated by Django 5.2 on 2025-04-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0005_remove_transaction_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiledger.recordaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='digiledger.transaction')),
            ],
            options={
                'unique_together': {('transaction', 'source_account')},
            },
        ),
    ]
