# Generated by Django 5.2 on 2025-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0006_transactionsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accGroup_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
