# Generated by Django 5.2 on 2025-05-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0008_recordaccount_account_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordaccount',
            name='account_group',
        ),
        migrations.DeleteModel(
            name='RecordAccountGroup',
        ),
    ]
