# Generated by Django 5.2 on 2025-05-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0010_recordstatementgroup_recordtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordaccount',
            name='record_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digiledger.recordtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordaccount',
            name='statement_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digiledger.recordstatementgroup'),
            preserve_default=False,
        ),
    ]
