# Generated by Django 5.2 on 2025-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0011_recordaccount_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='link',
            field=models.CharField(default="{% url 'linkhere' %}", max_length=255),
            preserve_default=False,
        ),
    ]
