# Generated by Django 5.2 on 2025-05-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0012_permission_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='permission',
            name='link',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='perm_name',
        ),
    ]
