# Generated by Django 5.2 on 2025-05-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0013_integratedsystems_remove_permission_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integratedsystems',
            old_name='perm_name',
            new_name='sysName',
        ),
        migrations.RenameField(
            model_name='integratedsystems',
            old_name='link',
            new_name='url_link',
        ),
    ]
