# Generated by Django 5.2 on 2025-05-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0014_rename_perm_name_integratedsystems_sysname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntegratedSystems',
            new_name='IntegratedSystem',
        ),
    ]
