# Generated by Django 5.2 on 2025-05-18 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0015_rename_integratedsystems_integratedsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digiledger.integratedsystem'),
            preserve_default=False,
        ),
    ]
