# Generated by Django 5.2 on 2025-05-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiledger', '0017_latestrefid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestrefid',
            name='emsRefId',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='latestrefid',
            name='posRefId',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
