# Generated by Django 5.2 on 2025-05-26 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.itemgroup'),
            preserve_default=False,
        ),
    ]
