# Generated by Django 5.2 on 2025-05-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_item_itemgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemGroup',
        ),
    ]
